[theme]

# Primary accent color for interactive elements
primaryColor = "#073763"

# Background color for the main content area
backgroundColor = "#93c47d"

# Backgroundcolor used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#16537e"

# Color used for almost all text
textColor = "#000000"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace"."

font = "sans serif"
